USE CITI

CREATE TABLE USERS(
	USERID INT IDENTITY(1, 1) CONSTRAINT CHECK_USER_ID_NOT_NULL NOT NULL CONSTRAINT USER_ID_PK PRIMARY KEY,
	USERNAME VARCHAR(20) UNIQUE CONSTRAINT CHECK_USERNAME_NOT_NULL NOT NULL,
	PASSCODE VARCHAR(20) CONSTRAINT CHECK_PASSWORD_NOT_NULL NOT NULL,
	USERFNAME VARCHAR(20),
	USERLNAME VARCHAR(20),
	CONTACT VARCHAR(20),
	GENDER VaRCHAR(10),
	);

CREATE TABLE SECURITIES(
	SECID INT IDENTITY(1, 1) CONSTRAINT CHECK_SECID_NOT_NULL NOT NULL CONSTRAINT SECID_PK PRIMARY KEY,
	SECURITY_NAME VARCHAR(50) CONSTRAINT CHECK_NAME_NOT_NULL NOT NULL,
	ISSUER_NAME VARCHAR(50) CONSTRAINT CHECK_ISSUER_NOT_NULL NOT NULL,
	FACE_VALUE FLOAT CONSTRAINT CHECK_FACE_NOT_NULL NOT NULL,
	COUPON_RATE FLOAT CONSTRAINT CHECK_COUPON_NULL NULL,
	FREQUENCY INT CONSTRAINT CHECK_FREQUENCY_NOT_NULL NOT NULL,
	MATURITY_DATE DATE CONSTRAINT CHECK_MATURITY_NOT_NULL NOT NULL,
	DAY_COUNT_CONVENTION INT CONSTRAINT CHECK_DAY_NOT_NULL NOT NULL,
	--QUOTE_CONVENTION INT CHECK_QUOTE_NOT_NULL NOT NULL,
	--TODO: See if better solution to store multiple dates
	COUPON_DATES VARCHAR(30) CONSTRAINT CHECK_COUPON_NULL NULL,
	ISIN VARCHAR(20) CONSTRAINT ISIN_UQ UNIQUE CONSTRAINT CHECK_ISIN_NOT_NULL NOT NULL
	);

CREATE TABLE TRADES(
	TRADEID INT IDENTITY(1, 1) CONSTRAINT CHECK_TRADE_ID_NOT_NULL NOT NULL CONSTRAINT TRADE_ID_PK PRIMARY KEY,
	TRADE_DATE DATE CONSTRAINT CHECK_TRADE_DATE_NOT_NULL NOT NULL,
	TRADE_TIME TIME CONSTRAINT CHECK_TRADE_TIME_NOT_NULL NOT NULL,
	TRADE_TYPE VARCHAR(10) CONSTRAINT CHECK_TRADE_TYPE_NOT_NULL NOT NULL,
	TRADE_PRICE VARCHAR(20) CONSTRAINT CHECK_TRADE_PRICE_NOT_NULL NOT NULL,
	COUNTER_PARTY VARCHAR(20) CONSTRAINT CHECK_COUNTER_PARTY_NOT_NULL NOT NULL,
	SETTLEMENT_DATE DATE CONSTRAINT CHECK_SETTLEMENT_DATE_NOT_NULL NOT NULL,
	LAST_COUPON_DATE DATE CONSTRAINT CHECK_LAST_COUPON_DATE_NOT_NULL NOT NULL,
	TICKS FLOAT CONSTRAINT CHECK_TICKS_NOT_NULL NOT NULL,
	DIRTY_PRICE FLOAT CONSTRAINT CHECK_DIRTY_PRICE_NOT_NULL NOT NULL,
	CLEAN_PRICE FLOAT CONSTRAINT CHECK_CLEAN_PRICE_NOT_NULL NOT NULL,
	SECID INT CONSTRAINT CHECK_SECID_NOT_NULL NOT NULL CONSTRAINT SECID_FK REFERENCES SECURITIES(SECID),
	USERID INT CONSTRAINT CHECK_USERID_NOT_NULL NOT NULL CONSTRAINT USERID_FK REFERENCES USERS(USERID),
	);

CREATE TABLE ACCRUEDS(
	ACCID INT IDENTITY(1, 1) CONSTRAINT CHECK_ACC_ID_NOT_NULL NOT NULL CONSTRAINT ACC_ID_PK PRIMARY KEY,
	ACCRUED_INTEREST FLOAT CONSTRAINT CHECK_ACCRUED_INTEREST_NOT_NULL NOT NULL,
	MARKET_PRICE VARCHAR(20) CONSTRAINT CHECK_MARKET_PRICE_NOT_NULL NOT NULL,
	MARKET_YIELD FLOAT CONSTRAINT CHECK_MARKET_YIELD_NOT_NULL NOT NULL,
	TRADEID INT CONSTRAINT CHECK_TRADEID_NOT_NULL NOT NULL CONSTRAINT TRADEID_FK REFERENCES TRADES(TRADEID),
	);

	-- TODO: Remove code below this line
	SELECT*FROM SECURITIES
	SELECT* FROM USERS
	SELECT * FROM TRADES
	INSERT INTO USERS VALUES('manan','mananjain')

	UPDATE USERS SET USERS.PASSCODE='mahak', USERS.USERNAME='mahak' WHERE USERNAME='manan'

	DROP TABLE ACCRUEDS;
	DROP TABLE TRADES;
	DROP TABLE SECURITIES;
	DROP TABLE USERS;

	INSERT INTO USERS VALUES('Manan', 'Temp','manan','jain','234567','male');
	INSERT INTO USERS VALUES('Mahak', 'Temp',);
	INSERT INTO USERS VALUES('Nisha', 'Temp');
	INSERT INTO USERS VALUES('Dipendra', 'Temp');

	SELECT * FROM TRADES;
	SELECT * FROM INFORMATION_SCHEMA.TABLES
	SELECT * FROM ACCRUEDS
	SELECT * FROM USERS
	SELECT * FROM SECURITIES
	
	DROP TABLE SYSDIAGRAMS;
	
	INSERT INTO TRADES VALUES('2018-2-3','12:23:40','BUY','100-30','WED','2018-2-13','2017-2-12',.234,234.2,123.45,1,1)

INSERT INTO SECURITIES VALUES('WED','WED',23.12,23.12,12,'2018-2-3',12,'WES','QWE')
INSERT INTO ACCRUEDS VALUES(23.2,'SER',23.42,6) 

	


